# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AMPMK2TSRKBFOo59yfosQpnp8zhDyBBV
"""

!git clone https://github.com/ganyiwatakunda/fashion-recommender-system-1.git

!pip install tensorflow

!pip install tensor rt

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %cd fashion-recommender-system-1/

!python app.py

!python test.py



!python main.py

!streamlit run main.py